name: read-ICESat-2
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - notebook
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - pyproj
  - matplotlib
  - cartopy
  - mpi4py
  - gdal
  - h5py>=2.9=mpi
  - zarr
  - future
  - lxml
  - paramiko
  - scp
