name: icesat2_toolkit
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - notebook
  - boto3
  - cartopy
  - future
  - gdal
  - h5py>=2.9=mpi*
  - lxml
  - matplotlib
  - mpi4py
  - netCDF4
  - numpy
  - pandas
  - paramiko
  - pyproj
  - python-dateutil
  - scikit-learn
  - scipy
  - scp
  - zarr
  - pip:
     - git+https://github.com/tsutterley/yapc.git
