name: icesat2-docs
channels:
  - conda-forge
dependencies:
  - docutils
  - fontconfig
  - freetype
  - future
  - graphviz
  - lxml
  - numpy
  - numpydoc
  - paramiko
  - pip
  - pyproj
  - python>=3.6
  - python-dateutil
  - pyyaml
  - scipy
  - scp
  - sphinx
  - sphinx_rtd_theme
  - timescale
  - pip:
    - sphinx-argparse>=0.4
    - ..

