# This workflow will install Python dependencies and update the time files

name: Auto-Update Files

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 0'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libproj-dev proj-data proj-bin libgeos-dev
        sudo apt-get install libhdf5-dev libxml2-dev libxslt1-dev
        pip install --upgrade pip
        pip install --upgrade setuptools
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        pip install --upgrade scipy h5py zarr lxml pandas
    - name: Update required files
      run: |
        pip install --no-deps .
        pytest test/test_leap_seconds.py
    - name: Archive updated files
      uses: actions/upload-artifact@v2
      with:
        name: leap-seconds
        path: |
            icesat2_toolkit/data/leap-seconds.list
    - name: Check for changes
      id: changes
      run: |
        if [ -n "$(git status --porcelain)" ] ; then
            echo "::set-output name=detected::true";
            echo "::debug::Changes detected";
        else
            echo "::set-output name=detected::false";
            echo "::debug::No changes detected";
        fi
    - name: Create pull request
      if: steps.changes.outputs.detected == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        assignees: ${{ github.actor }}
        title: "data: automatic time updates"
